AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-cli-test
  
  Sample SAM Template for sam-cli-test

Globals:
  Function:
    Runtime: go1.x
    Timeout: 5
    Environment:
      Variables:
        DYNAMODB_ENDPOINT: ""
        DYNAMODB_TABLE_NAME: !Ref UserDynamoDBTable

Resources:
  UserGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/
      Handler: user
      Tracing: Active
      Policies: AmazonDynamoDBFullAccess
      Events:
        GetUser:
          Type: Api
          Properties:
            Path: /users/{id}
            Method: GET
  UserDynamoDBTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: Id
        Type: Number
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
